apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  labels:
    app: transaction
spec:
  selector:
    app: transaction
  ports:
    - name: grpc
      port: 50010
      targetPort: 50010
    - name: metrics
      port: 8000
      targetPort: 8000
  type: ClusterIP
