apiVersion: v1
kind: Service
metadata:
  name: car-service
  labels:
    app: car
spec:
  selector:
    app: car
  ports:
    - name: grpc
      port: 50008
      targetPort: 50008
    - name: metrics
      port: 8000
      targetPort: 8000
  type: ClusterIP
