apiVersion: v1
kind: Service
metadata:
  name: inspection-service
  labels:
    app: inspection
spec:
  selector:
    app: inspection
  ports:
    - name: grpc
      port: 50011
      targetPort: 50011
    - name: metrics
      port: 8000
      targetPort: 8000
  type: ClusterIP