apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: fc58182/gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50000
          name: http
        - containerPort: 8000
          name: metrics
        envFrom:
        - secretRef:
            name: all-credentials
        - secretRef:
            name: all-credentials
        env:
        - name: FLASK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: all-credentials
              key: FLASK_SECRET_KEY
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          tcpSocket:
            port: 50000
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 4



