apiVersion: v1
kind: Service
metadata:
  name: maintenance-service
  labels:
    app: maintenance
spec:
  selector:
    app: maintenance
  ports:
    - name: grpc
      port: 50012
      targetPort: 50012
    - name: metrics
      port: 8000
      targetPort: 8000
  type: ClusterIP
