apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: fc58182/user:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50007
          name: grpc
        - containerPort: 8000
          name: metrics
        envFrom:
        - secretRef:
            name: all-credentials
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          tcpSocket:
            port: 50007
          initialDelaySeconds: 10
          periodSeconds: 5
