apiVersion: v1
kind: Service
metadata:
  name: meeting-service
  labels:
    app: meeting
spec:
  selector:
    app: meeting
  ports:
    - name: grpc
      port: 50015
      targetPort: 50015
    - name: metrics
      port: 8000
      targetPort: 8000
  type: ClusterIP
